server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peach_sql?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mao0524@wang

# JWT 配置
jwt: # 这是一个顶层键
  secret: NjFkYjQ1ZjA1YjUxNGU3OTk4YTc1Y2I4YjI5ZDAyNTY4ZTRiYjE4Y2QxYjQ1YjUwY2QxYzU0YjEwMjA3NQ== # 缩进两个空格
  expiration: 3600000 # 缩进两个空格